#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpFlow.Android.Resource", IsApplication=true)]

namespace OpFlow.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::OpFlow.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::OpFlow.Android.Resource.String.Hello;
			global::Xamarin.Auth.Resource.Animation.slide_in_right = global::OpFlow.Android.Resource.Animation.slide_in_right;
			global::Xamarin.Auth.Resource.Animation.slide_out_left = global::OpFlow.Android.Resource.Animation.slide_out_left;
			global::Xamarin.Auth.Resource.Drawable.ic_arrow_back = global::OpFlow.Android.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth.Resource.Id.webview = global::OpFlow.Android.Resource.Id.webview;
			global::Xamarin.Auth.Resource.Layout.activity_webview = global::OpFlow.Android.Resource.Layout.activity_webview;
			global::Xamarin.Auth.Resource.String.ApplicationName = global::OpFlow.Android.Resource.String.ApplicationName;
			global::Xamarin.Auth.Resource.String.Hello = global::OpFlow.Android.Resource.String.Hello;
			global::Xamarin.Auth.Resource.String.title_activity_webview = global::OpFlow.Android.Resource.String.title_activity_webview;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int opflow_black = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int opflow_blue = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int opflow_white = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int DarkGreenCheckMark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int FingerprintIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int HighlightedRoundRectangle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_arrow_back = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_chat_grey_50_18dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_schedule_grey_50_18dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_search_grey_50_18dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_work_grey_50_18dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int OpFlowLogo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int RedExclamationPoint = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int RoundRectangle = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0025
			public const int DataHeader = 2131361829;
			
			// aapt resource value: 0x7f0a000a
			public const int DataRow = 2131361802;
			
			// aapt resource value: 0x7f0a0022
			public const int btnArticles = 2131361826;
			
			// aapt resource value: 0x7f0a001f
			public const int btnCases = 2131361823;
			
			// aapt resource value: 0x7f0a001d
			public const int btnCheckIn = 2131361821;
			
			// aapt resource value: 0x7f0a0024
			public const int btnCommunity = 2131361828;
			
			// aapt resource value: 0x7f0a0023
			public const int btnData = 2131361827;
			
			// aapt resource value: 0x7f0a0029
			public const int btnLogin = 2131361833;
			
			// aapt resource value: 0x7f0a0020
			public const int btnMetrics = 2131361824;
			
			// aapt resource value: 0x7f0a001e
			public const int btnSchedule = 2131361822;
			
			// aapt resource value: 0x7f0a002f
			public const int btnScheduleDate = 2131361839;
			
			// aapt resource value: 0x7f0a0004
			public const int btnSearch = 2131361796;
			
			// aapt resource value: 0x7f0a0021
			public const int btnToDoList = 2131361825;
			
			// aapt resource value: 0x7f0a0030
			public const int gvDailySchedule = 2131361840;
			
			// aapt resource value: 0x7f0a000d
			public const int gvScheduledProcedures = 2131361805;
			
			// aapt resource value: 0x7f0a0011
			public const int gvSurgeryUsers = 2131361809;
			
			// aapt resource value: 0x7f0a0036
			public const int ivAlerts = 2131361846;
			
			// aapt resource value: 0x7f0a0013
			public const int ivCheckInStatus = 2131361811;
			
			// aapt resource value: 0x7f0a0037
			public const int ivDelays = 2131361847;
			
			// aapt resource value: 0x7f0a0039
			public const int ivHeaderIcon = 2131361849;
			
			// aapt resource value: 0x7f0a0035
			public const int ivPrefCard = 2131361845;
			
			// aapt resource value: 0x7f0a0015
			public const int ivReviewStatus = 2131361813;
			
			// aapt resource value: 0x7f0a0017
			public const int ivRoleStatus = 2131361815;
			
			// aapt resource value: 0x7f0a001c
			public const int ivStatus = 2131361820;
			
			// aapt resource value: 0x7f0a0009
			public const int lvCaseDetails = 2131361801;
			
			// aapt resource value: 0x7f0a0019
			public const int lvFutureCases = 2131361817;
			
			// aapt resource value: 0x7f0a002b
			public const int mainFragment = 2131361835;
			
			// aapt resource value: 0x7f0a003f
			public const int menu_cases = 2131361855;
			
			// aapt resource value: 0x7f0a003d
			public const int menu_communicator = 2131361853;
			
			// aapt resource value: 0x7f0a0040
			public const int menu_edit = 2131361856;
			
			// aapt resource value: 0x7f0a0042
			public const int menu_preferences = 2131361858;
			
			// aapt resource value: 0x7f0a0041
			public const int menu_save = 2131361857;
			
			// aapt resource value: 0x7f0a003e
			public const int menu_schedule = 2131361854;
			
			// aapt resource value: 0x7f0a003c
			public const int menu_search = 2131361852;
			
			// aapt resource value: 0x7f0a002c
			public const int nav_toolbar = 2131361836;
			
			// aapt resource value: 0x7f0a0005
			public const int pnlCaseDetail = 2131361797;
			
			// aapt resource value: 0x7f0a0031
			public const int pnlLayout = 2131361841;
			
			// aapt resource value: 0x7f0a000c
			public const int pnlScheduledProceduresHeaders = 2131361804;
			
			// aapt resource value: 0x7f0a0010
			public const int spnAssignment = 2131361808;
			
			// aapt resource value: 0x7f0a002e
			public const int spnRoom = 2131361838;
			
			// aapt resource value: 0x7f0a000f
			public const int swtCheckIn = 2131361807;
			
			// aapt resource value: 0x7f0a002d
			public const int swtSurgeon = 2131361837;
			
			// aapt resource value: 0x7f0a002a
			public const int toolbar = 2131361834;
			
			// aapt resource value: 0x7f0a000e
			public const int txtCard = 2131361806;
			
			// aapt resource value: 0x7f0a0007
			public const int txtCase = 2131361799;
			
			// aapt resource value: 0x7f0a001b
			public const int txtCaseTime = 2131361819;
			
			// aapt resource value: 0x7f0a0014
			public const int txtDelay = 2131361812;
			
			// aapt resource value: 0x7f0a0038
			public const int txtDelayAmt = 2131361848;
			
			// aapt resource value: 0x7f0a0018
			public const int txtDelayStatus = 2131361816;
			
			// aapt resource value: 0x7f0a0026
			public const int txtError = 2131361830;
			
			// aapt resource value: 0x7f0a003a
			public const int txtHeaderApplication = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public const int txtHeaderUser = 2131361851;
			
			// aapt resource value: 0x7f0a000b
			public const int txtItemText = 2131361803;
			
			// aapt resource value: 0x7f0a0033
			public const int txtLocation = 2131361843;
			
			// aapt resource value: 0x7f0a0028
			public const int txtPassword = 2131361832;
			
			// aapt resource value: 0x7f0a0002
			public const int txtPatientAge = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int txtPatientBMI = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int txtPatientName = 2131361793;
			
			// aapt resource value: 0x7f0a0034
			public const int txtPatientSex = 2131361844;
			
			// aapt resource value: 0x7f0a001a
			public const int txtProcedure = 2131361818;
			
			// aapt resource value: 0x7f0a0008
			public const int txtReferMD = 2131361800;
			
			// aapt resource value: 0x7f0a0016
			public const int txtRole = 2131361814;
			
			// aapt resource value: 0x7f0a0012
			public const int txtRoleName = 2131361810;
			
			// aapt resource value: 0x7f0a0006
			public const int txtSurgeon = 2131361798;
			
			// aapt resource value: 0x7f0a0032
			public const int txtTime = 2131361842;
			
			// aapt resource value: 0x7f0a0027
			public const int txtUserName = 2131361831;
			
			// aapt resource value: 0x7f0a0000
			public const int webview = 2131361792;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int SpinnerHeight = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CaseDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CaseDetailListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CheckIn = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CheckInGrid = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CheckInOverviewGrid = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FutureCase = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FutureCaseListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int HomeScreen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ListGroup = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Login = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Schedule = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ScheduleGrid = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Toolbar = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int nav_menu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int option_menu = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int empty_string = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int title_activity_webview = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int OpFlowTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ToolBarStyle = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
