#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpFlow.Android.Resource", IsApplication=true)]

namespace OpFlow.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int opflow_blue = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int DarkGreenCheckMark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int HighlightedRoundRectangle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int OpFlowLogo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int RedExclamationPoint = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int RoundRectangle = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070025
			public const int btnArticles = 2131165221;
			
			// aapt resource value: 0x7f070022
			public const int btnCases = 2131165218;
			
			// aapt resource value: 0x7f070020
			public const int btnCheckIn = 2131165216;
			
			// aapt resource value: 0x7f070027
			public const int btnCommunity = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int btnData = 2131165222;
			
			// aapt resource value: 0x7f07001f
			public const int btnLogin = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int btnMetrics = 2131165219;
			
			// aapt resource value: 0x7f070021
			public const int btnSchedule = 2131165217;
			
			// aapt resource value: 0x7f070028
			public const int btnScheduleDate = 2131165224;
			
			// aapt resource value: 0x7f070000
			public const int btnSearch = 2131165184;
			
			// aapt resource value: 0x7f070024
			public const int btnToDoList = 2131165220;
			
			// aapt resource value: 0x7f070029
			public const int gvDailySchedule = 2131165225;
			
			// aapt resource value: 0x7f070015
			public const int gvScheduledProcedures = 2131165205;
			
			// aapt resource value: 0x7f07002f
			public const int ivAlerts = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int ivDelays = 2131165232;
			
			// aapt resource value: 0x7f07002e
			public const int ivPrefCard = 2131165230;
			
			// aapt resource value: 0x7f07001b
			public const int ivStatus = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int lvFutureCases = 2131165208;
			
			// aapt resource value: 0x7f070001
			public const int pnlCaseDetail = 2131165185;
			
			// aapt resource value: 0x7f07002a
			public const int pnlLayout = 2131165226;
			
			// aapt resource value: 0x7f07000e
			public const int swtAllergies = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int swtLabResults = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int swtMedicalHistory = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int swtMedications = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int swtPastProcedureResults = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int swtRiskFactors = 2131165194;
			
			// aapt resource value: 0x7f070014
			public const int swtScheduledProcedures = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int swtSurgeon = 2131165207;
			
			// aapt resource value: 0x7f07000f
			public const int txtAllergies = 2131165199;
			
			// aapt resource value: 0x7f070016
			public const int txtCard = 2131165206;
			
			// aapt resource value: 0x7f070003
			public const int txtCase = 2131165187;
			
			// aapt resource value: 0x7f07001a
			public const int txtCaseTime = 2131165210;
			
			// aapt resource value: 0x7f070031
			public const int txtDelayAmt = 2131165233;
			
			// aapt resource value: 0x7f07001c
			public const int txtError = 2131165212;
			
			// aapt resource value: 0x7f070011
			public const int txtLabResults = 2131165201;
			
			// aapt resource value: 0x7f07002c
			public const int txtLocation = 2131165228;
			
			// aapt resource value: 0x7f070009
			public const int txtMedicalHistory = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int txtMedications = 2131165197;
			
			// aapt resource value: 0x7f07001e
			public const int txtPassword = 2131165214;
			
			// aapt resource value: 0x7f070013
			public const int txtPastProcedureResults = 2131165203;
			
			// aapt resource value: 0x7f070006
			public const int txtPatientAge = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int txtPatientBMI = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int txtPatientName = 2131165189;
			
			// aapt resource value: 0x7f07002d
			public const int txtPatientSex = 2131165229;
			
			// aapt resource value: 0x7f070019
			public const int txtProcedure = 2131165209;
			
			// aapt resource value: 0x7f070004
			public const int txtReferMD = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int txtRiskFactors = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int txtSurgeon = 2131165186;
			
			// aapt resource value: 0x7f07002b
			public const int txtTime = 2131165227;
			
			// aapt resource value: 0x7f07001d
			public const int txtUserName = 2131165213;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CaseDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CheckIn = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FutureCase = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FutureCaseListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Schedule = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ScheduleGrid = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int OpFlowTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
