#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpFlow.Android.Resource", IsApplication=true)]

namespace OpFlow.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int opflow_black = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int opflow_blue = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int opflow_white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int DarkGreenCheckMark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int FingerprintIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int HighlightedRoundRectangle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_chat_grey_50_18dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_schedule_grey_50_18dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_search_grey_50_18dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_work_grey_50_18dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int OpFlowLogo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int RedExclamationPoint = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int RoundRectangle = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090024
			public const int DataHeader = 2131296292;
			
			// aapt resource value: 0x7f090009
			public const int DataRow = 2131296265;
			
			// aapt resource value: 0x7f090021
			public const int btnArticles = 2131296289;
			
			// aapt resource value: 0x7f09001e
			public const int btnCases = 2131296286;
			
			// aapt resource value: 0x7f09001c
			public const int btnCheckIn = 2131296284;
			
			// aapt resource value: 0x7f090023
			public const int btnCommunity = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int btnData = 2131296290;
			
			// aapt resource value: 0x7f090028
			public const int btnLogin = 2131296296;
			
			// aapt resource value: 0x7f09001f
			public const int btnMetrics = 2131296287;
			
			// aapt resource value: 0x7f09001d
			public const int btnSchedule = 2131296285;
			
			// aapt resource value: 0x7f09002c
			public const int btnScheduleDate = 2131296300;
			
			// aapt resource value: 0x7f090003
			public const int btnSearch = 2131296259;
			
			// aapt resource value: 0x7f090020
			public const int btnToDoList = 2131296288;
			
			// aapt resource value: 0x7f09002d
			public const int gvDailySchedule = 2131296301;
			
			// aapt resource value: 0x7f09000c
			public const int gvScheduledProcedures = 2131296268;
			
			// aapt resource value: 0x7f090010
			public const int gvSurgeryUsers = 2131296272;
			
			// aapt resource value: 0x7f090033
			public const int ivAlerts = 2131296307;
			
			// aapt resource value: 0x7f090012
			public const int ivCheckInStatus = 2131296274;
			
			// aapt resource value: 0x7f090034
			public const int ivDelays = 2131296308;
			
			// aapt resource value: 0x7f090032
			public const int ivPrefCard = 2131296306;
			
			// aapt resource value: 0x7f090014
			public const int ivReviewStatus = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int ivRoleStatus = 2131296278;
			
			// aapt resource value: 0x7f09001b
			public const int ivStatus = 2131296283;
			
			// aapt resource value: 0x7f090008
			public const int lvCaseDetails = 2131296264;
			
			// aapt resource value: 0x7f090018
			public const int lvFutureCases = 2131296280;
			
			// aapt resource value: 0x7f09002a
			public const int mainFragment = 2131296298;
			
			// aapt resource value: 0x7f09003b
			public const int menu_cases = 2131296315;
			
			// aapt resource value: 0x7f090039
			public const int menu_communicator = 2131296313;
			
			// aapt resource value: 0x7f09003c
			public const int menu_edit = 2131296316;
			
			// aapt resource value: 0x7f09003e
			public const int menu_preferences = 2131296318;
			
			// aapt resource value: 0x7f09003d
			public const int menu_save = 2131296317;
			
			// aapt resource value: 0x7f09003a
			public const int menu_schedule = 2131296314;
			
			// aapt resource value: 0x7f090038
			public const int menu_search = 2131296312;
			
			// aapt resource value: 0x7f09002b
			public const int nav_toolbar = 2131296299;
			
			// aapt resource value: 0x7f090004
			public const int pnlCaseDetail = 2131296260;
			
			// aapt resource value: 0x7f09002e
			public const int pnlLayout = 2131296302;
			
			// aapt resource value: 0x7f09000b
			public const int pnlScheduledProceduresHeaders = 2131296267;
			
			// aapt resource value: 0x7f09000f
			public const int spnAssignment = 2131296271;
			
			// aapt resource value: 0x7f09000e
			public const int swtCheckIn = 2131296270;
			
			// aapt resource value: 0x7f090029
			public const int toolbar = 2131296297;
			
			// aapt resource value: 0x7f09000d
			public const int txtCard = 2131296269;
			
			// aapt resource value: 0x7f090006
			public const int txtCase = 2131296262;
			
			// aapt resource value: 0x7f09001a
			public const int txtCaseTime = 2131296282;
			
			// aapt resource value: 0x7f090013
			public const int txtDelay = 2131296275;
			
			// aapt resource value: 0x7f090035
			public const int txtDelayAmt = 2131296309;
			
			// aapt resource value: 0x7f090017
			public const int txtDelayStatus = 2131296279;
			
			// aapt resource value: 0x7f090025
			public const int txtError = 2131296293;
			
			// aapt resource value: 0x7f090036
			public const int txtHeaderApplication = 2131296310;
			
			// aapt resource value: 0x7f090037
			public const int txtHeaderUser = 2131296311;
			
			// aapt resource value: 0x7f09000a
			public const int txtItemText = 2131296266;
			
			// aapt resource value: 0x7f090030
			public const int txtLocation = 2131296304;
			
			// aapt resource value: 0x7f090027
			public const int txtPassword = 2131296295;
			
			// aapt resource value: 0x7f090001
			public const int txtPatientAge = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int txtPatientBMI = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int txtPatientName = 2131296256;
			
			// aapt resource value: 0x7f090031
			public const int txtPatientSex = 2131296305;
			
			// aapt resource value: 0x7f090019
			public const int txtProcedure = 2131296281;
			
			// aapt resource value: 0x7f090007
			public const int txtReferMD = 2131296263;
			
			// aapt resource value: 0x7f090015
			public const int txtRole = 2131296277;
			
			// aapt resource value: 0x7f090011
			public const int txtRoleName = 2131296273;
			
			// aapt resource value: 0x7f090005
			public const int txtSurgeon = 2131296261;
			
			// aapt resource value: 0x7f09002f
			public const int txtTime = 2131296303;
			
			// aapt resource value: 0x7f090026
			public const int txtUserName = 2131296294;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int SpinnerHeight = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CaseDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CaseDetailListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CheckIn = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CheckInGrid = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CheckInOverviewGrid = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FutureCase = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FutureCaseListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HomeScreen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListGroup = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Login = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Schedule = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ScheduleGrid = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Toolbar = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int nav_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int option_menu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int empty_string = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int ActionBarTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int OpFlowTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int ToolBarStyle = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
