#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpFlow.AndroidApp.Resource", IsApplication=true)]

namespace OpFlow.AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::OpFlow.AndroidApp.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::OpFlow.AndroidApp.Resource.String.Hello;
			global::Xamarin.Auth.Resource.Animation.slide_in_right = global::OpFlow.AndroidApp.Resource.Animation.slide_in_right;
			global::Xamarin.Auth.Resource.Animation.slide_out_left = global::OpFlow.AndroidApp.Resource.Animation.slide_out_left;
			global::Xamarin.Auth.Resource.Drawable.ic_arrow_back = global::OpFlow.AndroidApp.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth.Resource.Id.webview = global::OpFlow.AndroidApp.Resource.Id.webview;
			global::Xamarin.Auth.Resource.Layout.activity_webview = global::OpFlow.AndroidApp.Resource.Layout.activity_webview;
			global::Xamarin.Auth.Resource.String.ApplicationName = global::OpFlow.AndroidApp.Resource.String.ApplicationName;
			global::Xamarin.Auth.Resource.String.Hello = global::OpFlow.AndroidApp.Resource.String.Hello;
			global::Xamarin.Auth.Resource.String.title_activity_webview = global::OpFlow.AndroidApp.Resource.String.title_activity_webview;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int date = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int opflow_black = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int opflow_blue = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int opflow_highlight = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int opflow_lightgray = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int opflow_white = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int DarkGreenCheckMark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Divider = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int FingerprintIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int HighlightedRoundRectangle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_arrow_back = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_chat_black_18dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_chat_grey_50_18dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_chat_grey_800_18dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_check_circle_green_A700_18dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_create_black_18dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_home_grey_800_18dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_hotel_black_18dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_move_to_inbox_black_18dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_payment_black_18dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_person_black_18dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_play_arrow_black_18dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_schedule_grey_50_18dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_schedule_grey_800_18dp = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_search_grey_50_18dp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_search_grey_800_18dp = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_settings_black_18dp = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_work_grey_50_18dp = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_work_grey_800_18dp = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int infinity = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int OpFlowLogo = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int RedExclamationPoint = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int RoundGrayRectangle = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int RoundRectangle = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0037
			public const int DataHeader = 2131361847;
			
			// aapt resource value: 0x7f0a000b
			public const int DataRow = 2131361803;
			
			// aapt resource value: 0x7f0a0034
			public const int btnArticles = 2131361844;
			
			// aapt resource value: 0x7f0a0031
			public const int btnCases = 2131361841;
			
			// aapt resource value: 0x7f0a002f
			public const int btnCheckIn = 2131361839;
			
			// aapt resource value: 0x7f0a0036
			public const int btnCommunity = 2131361846;
			
			// aapt resource value: 0x7f0a0035
			public const int btnData = 2131361845;
			
			// aapt resource value: 0x7f0a0013
			public const int btnDebrief = 2131361811;
			
			// aapt resource value: 0x7f0a003b
			public const int btnLogin = 2131361851;
			
			// aapt resource value: 0x7f0a0032
			public const int btnMetrics = 2131361842;
			
			// aapt resource value: 0x7f0a0030
			public const int btnSchedule = 2131361840;
			
			// aapt resource value: 0x7f0a001d
			public const int btnSearch = 2131361821;
			
			// aapt resource value: 0x7f0a0033
			public const int btnToDoList = 2131361843;
			
			// aapt resource value: 0x7f0a004d
			public const int gvDailySchedule = 2131361869;
			
			// aapt resource value: 0x7f0a000e
			public const int gvScheduledProcedures = 2131361806;
			
			// aapt resource value: 0x7f0a0024
			public const int gvSurgeryUsers = 2131361828;
			
			// aapt resource value: 0x7f0a0052
			public const int ivAlerts = 2131361874;
			
			// aapt resource value: 0x7f0a0026
			public const int ivCheckInStatus = 2131361830;
			
			// aapt resource value: 0x7f0a0053
			public const int ivDelays = 2131361875;
			
			// aapt resource value: 0x7f0a0056
			public const int ivHeaderIcon = 2131361878;
			
			// aapt resource value: 0x7f0a0051
			public const int ivPrefCard = 2131361873;
			
			// aapt resource value: 0x7f0a0028
			public const int ivReviewStatus = 2131361832;
			
			// aapt resource value: 0x7f0a002a
			public const int ivRoleStatus = 2131361834;
			
			// aapt resource value: 0x7f0a002e
			public const int ivStatus = 2131361838;
			
			// aapt resource value: 0x7f0a0043
			public const int ivWeekBack = 2131361859;
			
			// aapt resource value: 0x7f0a0045
			public const int ivWeekForward = 2131361861;
			
			// aapt resource value: 0x7f0a0008
			public const int lvCaseDetails = 2131361800;
			
			// aapt resource value: 0x7f0a002c
			public const int lvFutureCases = 2131361836;
			
			// aapt resource value: 0x7f0a003d
			public const int mainFragment = 2131361853;
			
			// aapt resource value: 0x7f0a005c
			public const int menu_cases = 2131361884;
			
			// aapt resource value: 0x7f0a005a
			public const int menu_communicator = 2131361882;
			
			// aapt resource value: 0x7f0a005d
			public const int menu_edit = 2131361885;
			
			// aapt resource value: 0x7f0a005f
			public const int menu_preferences = 2131361887;
			
			// aapt resource value: 0x7f0a005e
			public const int menu_save = 2131361886;
			
			// aapt resource value: 0x7f0a005b
			public const int menu_schedule = 2131361883;
			
			// aapt resource value: 0x7f0a0059
			public const int menu_search = 2131361881;
			
			// aapt resource value: 0x7f0a003f
			public const int navHome = 2131361855;
			
			// aapt resource value: 0x7f0a003e
			public const int navSchedule = 2131361854;
			
			// aapt resource value: 0x7f0a0040
			public const int navSearch = 2131361856;
			
			// aapt resource value: 0x7f0a0015
			public const int pnlCard = 2131361813;
			
			// aapt resource value: 0x7f0a001e
			public const int pnlCaseDetail = 2131361822;
			
			// aapt resource value: 0x7f0a0017
			public const int pnlCommunicator = 2131361815;
			
			// aapt resource value: 0x7f0a0009
			public const int pnlConfirmButton = 2131361801;
			
			// aapt resource value: 0x7f0a0016
			public const int pnlFlow = 2131361814;
			
			// aapt resource value: 0x7f0a004e
			public const int pnlLayout = 2131361870;
			
			// aapt resource value: 0x7f0a0055
			public const int pnlOpenCase = 2131361877;
			
			// aapt resource value: 0x7f0a0014
			public const int pnlPatient = 2131361812;
			
			// aapt resource value: 0x7f0a0050
			public const int pnlScheduledCase = 2131361872;
			
			// aapt resource value: 0x7f0a000d
			public const int pnlScheduledProceduresHeaders = 2131361805;
			
			// aapt resource value: 0x7f0a0023
			public const int spnAssignment = 2131361827;
			
			// aapt resource value: 0x7f0a0042
			public const int spnRoom = 2131361858;
			
			// aapt resource value: 0x7f0a0022
			public const int swtCheckIn = 2131361826;
			
			// aapt resource value: 0x7f0a0041
			public const int swtSurgeon = 2131361857;
			
			// aapt resource value: 0x7f0a003c
			public const int toolbar = 2131361852;
			
			// aapt resource value: 0x7f0a001a
			public const int txtAnesName = 2131361818;
			
			// aapt resource value: 0x7f0a0021
			public const int txtCard = 2131361825;
			
			// aapt resource value: 0x7f0a0020
			public const int txtCase = 2131361824;
			
			// aapt resource value: 0x7f0a002d
			public const int txtCaseTime = 2131361837;
			
			// aapt resource value: 0x7f0a0019
			public const int txtCirculatorName = 2131361817;
			
			// aapt resource value: 0x7f0a000a
			public const int txtConfirmText = 2131361802;
			
			// aapt resource value: 0x7f0a0044
			public const int txtCurrentWeek = 2131361860;
			
			// aapt resource value: 0x7f0a0027
			public const int txtDelay = 2131361831;
			
			// aapt resource value: 0x7f0a0054
			public const int txtDelayAmt = 2131361876;
			
			// aapt resource value: 0x7f0a002b
			public const int txtDelayStatus = 2131361835;
			
			// aapt resource value: 0x7f0a0038
			public const int txtError = 2131361848;
			
			// aapt resource value: 0x7f0a0012
			public const int txtFlowStep = 2131361810;
			
			// aapt resource value: 0x7f0a0057
			public const int txtHeaderApplication = 2131361879;
			
			// aapt resource value: 0x7f0a0058
			public const int txtHeaderUser = 2131361880;
			
			// aapt resource value: 0x7f0a000c
			public const int txtItemText = 2131361804;
			
			// aapt resource value: 0x7f0a0003
			public const int txtLocation = 2131361795;
			
			// aapt resource value: 0x7f0a003a
			public const int txtPassword = 2131361850;
			
			// aapt resource value: 0x7f0a0004
			public const int txtPatientAge = 2131361796;
			
			// aapt resource value: 0x7f0a0006
			public const int txtPatientBMI = 2131361798;
			
			// aapt resource value: 0x7f0a0011
			public const int txtPatientInfo = 2131361809;
			
			// aapt resource value: 0x7f0a0001
			public const int txtPatientName = 2131361793;
			
			// aapt resource value: 0x7f0a0005
			public const int txtPatientSex = 2131361797;
			
			// aapt resource value: 0x7f0a0007
			public const int txtProcedure = 2131361799;
			
			// aapt resource value: 0x7f0a0002
			public const int txtProcedureStart = 2131361794;
			
			// aapt resource value: 0x7f0a001c
			public const int txtRepName = 2131361820;
			
			// aapt resource value: 0x7f0a0029
			public const int txtRole = 2131361833;
			
			// aapt resource value: 0x7f0a0025
			public const int txtRoleName = 2131361829;
			
			// aapt resource value: 0x7f0a0010
			public const int txtRoom = 2131361808;
			
			// aapt resource value: 0x7f0a001b
			public const int txtScrubName = 2131361819;
			
			// aapt resource value: 0x7f0a000f
			public const int txtStartTime = 2131361807;
			
			// aapt resource value: 0x7f0a001f
			public const int txtSurgeon = 2131361823;
			
			// aapt resource value: 0x7f0a0018
			public const int txtSurgeonName = 2131361816;
			
			// aapt resource value: 0x7f0a004f
			public const int txtTime = 2131361871;
			
			// aapt resource value: 0x7f0a0039
			public const int txtUserName = 2131361849;
			
			// aapt resource value: 0x7f0a004b
			public const int txtWeekFriday = 2131361867;
			
			// aapt resource value: 0x7f0a0047
			public const int txtWeekMonday = 2131361863;
			
			// aapt resource value: 0x7f0a004c
			public const int txtWeekSaturday = 2131361868;
			
			// aapt resource value: 0x7f0a0046
			public const int txtWeekSunday = 2131361862;
			
			// aapt resource value: 0x7f0a004a
			public const int txtWeekThursday = 2131361866;
			
			// aapt resource value: 0x7f0a0048
			public const int txtWeekTuesday = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public const int txtWeekWednesday = 2131361865;
			
			// aapt resource value: 0x7f0a0000
			public const int webview = 2131361792;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int SpinnerHeight = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CaseDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CaseDetailListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CaseNavigate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CheckIn = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CheckInGrid = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CheckInOverviewGrid = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FutureCase = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int FutureCaseListItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int HomeScreen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ListGroup = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Login = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Schedule = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ScheduleGrid = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Toolbar = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int nav_menu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int option_menu = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int empty_string = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int title_activity_webview = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int OpFlowTheme = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int TextView_Calendar = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int TextView_Header = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int ToolBarStyle = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] DatePicker = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int DatePicker_date = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
